// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CollapseTree
arma::umat CollapseTree(arma::umat edgeMat, arma::uword tipNum, arma::uvec f, arma::uvec t);
RcppExport SEXP PhyloProfile_CollapseTree(SEXP edgeMatSEXP, SEXP tipNumSEXP, SEXP fSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type edgeMat(edgeMatSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type tipNum(tipNumSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type f(fSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(CollapseTree(edgeMat, tipNum, f, t));
    return rcpp_result_gen;
END_RCPP
}
// isTwoRowsEqual
bool isTwoRowsEqual(arma::umat m);
RcppExport SEXP PhyloProfile_isTwoRowsEqual(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(isTwoRowsEqual(m));
    return rcpp_result_gen;
END_RCPP
}
// InferGainNodes
arma::uvec InferGainNodes(Rcpp::List gainList);
RcppExport SEXP PhyloProfile_InferGainNodes(SEXP gainListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type gainList(gainListSEXP);
    rcpp_result_gen = Rcpp::wrap(InferGainNodes(gainList));
    return rcpp_result_gen;
END_RCPP
}
// InferEdge
arma::imat InferEdge(arma::umat edgeMat, Rcpp::List tipPath, Rcpp::NumericVector pr);
RcppExport SEXP PhyloProfile_InferEdge(SEXP edgeMatSEXP, SEXP tipPathSEXP, SEXP prSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type edgeMat(edgeMatSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type tipPath(tipPathSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pr(prSEXP);
    rcpp_result_gen = Rcpp::wrap(InferEdge(edgeMat, tipPath, pr));
    return rcpp_result_gen;
END_RCPP
}
// DolloDist
arma::uword DolloDist(arma::umat edgeMat, Rcpp::List tipPath, Rcpp::NumericVector f, Rcpp::NumericVector t);
RcppExport SEXP PhyloProfile_DolloDist(SEXP edgeMatSEXP, SEXP tipPathSEXP, SEXP fSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type edgeMat(edgeMatSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type tipPath(tipPathSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type f(fSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(DolloDist(edgeMat, tipPath, f, t));
    return rcpp_result_gen;
END_RCPP
}
// MergeList
arma::uvec MergeList(Rcpp::List x);
RcppExport SEXP PhyloProfile_MergeList(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(MergeList(x));
    return rcpp_result_gen;
END_RCPP
}
// SimMIBin
double SimMIBin(arma::vec f, arma::vec t);
RcppExport SEXP PhyloProfile_SimMIBin(SEXP fSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type f(fSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(SimMIBin(f, t));
    return rcpp_result_gen;
END_RCPP
}
// eachMI
double eachMI(double p1, double p2, double p3, double n);
RcppExport SEXP PhyloProfile_eachMI(SEXP p1SEXP, SEXP p2SEXP, SEXP p3SEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< double >::type p3(p3SEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(eachMI(p1, p2, p3, n));
    return rcpp_result_gen;
END_RCPP
}
// SimMIConti
double SimMIConti(arma::vec f, arma::vec t, arma::uword bin);
RcppExport SEXP PhyloProfile_SimMIConti(SEXP fSEXP, SEXP tSEXP, SEXP binSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type f(fSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type bin(binSEXP);
    rcpp_result_gen = Rcpp::wrap(SimMIConti(f, t, bin));
    return rcpp_result_gen;
END_RCPP
}
// Info
double Info(arma::uvec v, double n);
RcppExport SEXP PhyloProfile_Info(SEXP vSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(Info(v, n));
    return rcpp_result_gen;
END_RCPP
}
// HistTwo
arma::uvec HistTwo(arma::vec x, arma::vec y, arma::uword bin);
RcppExport SEXP PhyloProfile_HistTwo(SEXP xSEXP, SEXP ySEXP, SEXP binSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::uword >::type bin(binSEXP);
    rcpp_result_gen = Rcpp::wrap(HistTwo(x, y, bin));
    return rcpp_result_gen;
END_RCPP
}
// FindInter
arma::uvec FindInter(arma::vec x, arma::vec interval);
RcppExport SEXP PhyloProfile_FindInter(SEXP xSEXP, SEXP intervalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type interval(intervalSEXP);
    rcpp_result_gen = Rcpp::wrap(FindInter(x, interval));
    return rcpp_result_gen;
END_RCPP
}
// FindInterSingle
arma::uword FindInterSingle(double value, arma::vec interval);
RcppExport SEXP PhyloProfile_FindInterSingle(SEXP valueSEXP, SEXP intervalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type interval(intervalSEXP);
    rcpp_result_gen = Rcpp::wrap(FindInterSingle(value, interval));
    return rcpp_result_gen;
END_RCPP
}
// gInter
arma::vec gInter(arma::vec x, arma::uword bin);
RcppExport SEXP PhyloProfile_gInter(SEXP xSEXP, SEXP binSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type bin(binSEXP);
    rcpp_result_gen = Rcpp::wrap(gInter(x, bin));
    return rcpp_result_gen;
END_RCPP
}
// CountRepeat
arma::uvec CountRepeat(arma::uvec x);
RcppExport SEXP PhyloProfile_CountRepeat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(CountRepeat(x));
    return rcpp_result_gen;
END_RCPP
}
// NPPNorm
Rcpp::NumericMatrix NPPNorm(Rcpp::NumericMatrix rawBitM, double bitCutoff, double bitReset, double minConserve);
RcppExport SEXP PhyloProfile_NPPNorm(SEXP rawBitMSEXP, SEXP bitCutoffSEXP, SEXP bitResetSEXP, SEXP minConserveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type rawBitM(rawBitMSEXP);
    Rcpp::traits::input_parameter< double >::type bitCutoff(bitCutoffSEXP);
    Rcpp::traits::input_parameter< double >::type bitReset(bitResetSEXP);
    Rcpp::traits::input_parameter< double >::type minConserve(minConserveSEXP);
    rcpp_result_gen = Rcpp::wrap(NPPNorm(rawBitM, bitCutoff, bitReset, minConserve));
    return rcpp_result_gen;
END_RCPP
}
// SVDNorm
Rcpp::NumericMatrix SVDNorm(Rcpp::NumericMatrix rawBitM, double bitCutoff, double bitReset, double minConserve, double trimming);
RcppExport SEXP PhyloProfile_SVDNorm(SEXP rawBitMSEXP, SEXP bitCutoffSEXP, SEXP bitResetSEXP, SEXP minConserveSEXP, SEXP trimmingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type rawBitM(rawBitMSEXP);
    Rcpp::traits::input_parameter< double >::type bitCutoff(bitCutoffSEXP);
    Rcpp::traits::input_parameter< double >::type bitReset(bitResetSEXP);
    Rcpp::traits::input_parameter< double >::type minConserve(minConserveSEXP);
    Rcpp::traits::input_parameter< double >::type trimming(trimmingSEXP);
    rcpp_result_gen = Rcpp::wrap(SVDNorm(rawBitM, bitCutoff, bitReset, minConserve, trimming));
    return rcpp_result_gen;
END_RCPP
}
// SVDPhy
Rcpp::NumericMatrix SVDPhy(Rcpp::NumericMatrix bitM, double bitReset, double minConserve, double trimming);
RcppExport SEXP PhyloProfile_SVDPhy(SEXP bitMSEXP, SEXP bitResetSEXP, SEXP minConserveSEXP, SEXP trimmingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type bitM(bitMSEXP);
    Rcpp::traits::input_parameter< double >::type bitReset(bitResetSEXP);
    Rcpp::traits::input_parameter< double >::type minConserve(minConserveSEXP);
    Rcpp::traits::input_parameter< double >::type trimming(trimmingSEXP);
    rcpp_result_gen = Rcpp::wrap(SVDPhy(bitM, bitReset, minConserve, trimming));
    return rcpp_result_gen;
END_RCPP
}
// SimCor
double SimCor(arma::vec f, arma::vec t);
RcppExport SEXP PhyloProfile_SimCor(SEXP fSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type f(fSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(SimCor(f, t));
    return rcpp_result_gen;
END_RCPP
}
// SimJaccard
double SimJaccard(arma::vec f, arma::vec t);
RcppExport SEXP PhyloProfile_SimJaccard(SEXP fSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type f(fSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(SimJaccard(f, t));
    return rcpp_result_gen;
END_RCPP
}
// DistHamming
double DistHamming(arma::vec f, arma::vec t);
RcppExport SEXP PhyloProfile_DistHamming(SEXP fSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type f(fSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(DistHamming(f, t));
    return rcpp_result_gen;
END_RCPP
}
// DistEuclidean
double DistEuclidean(arma::vec f, arma::vec t);
RcppExport SEXP PhyloProfile_DistEuclidean(SEXP fSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type f(fSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(DistEuclidean(f, t));
    return rcpp_result_gen;
END_RCPP
}
